apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-admin-member-submit
spec:
  reasonSelector:
    reasonType: admin-member-submit
    language: default
  template:
    title: "有新的成员申请，请审核！"
    rawBody: |
      有新的成员申请，请审核：

      账号名称：${displayName}
      邮箱：${email}
      所属学校：${school}
      QQ号：${qq}
      分组：${groupName}

    htmlBody: |
      <div class="content">
        <div class="head">
          <p class="honorific">${subscriber.displayName} 你好：</p>
        </div>
        <div class="body">
          <p>有新的成员申请，请审核：</p>
          <div class="summary">
            <p>账号名称：${displayName}</p>
            <p>邮箱：${email}</p>
            <p>所属学校：${school}</p>
            <p>QQ号：${qq}</p>
            <p>分组：${groupName}</p>
          </div>
          <p><a href="${reviewUrl}" target="_blank" rel="noopener noreferrer">前往查看</a></p>
        </div>
        <div></div>
      </div>
---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-user-member-submit
spec:
  reasonSelector:
    reasonType: user-member-submit
    language: default
  template:
    title: "您的成员申请已提交。"
    rawBody: |
      您的成员申请已提交，请等待审核！

    htmlBody: |
      <div class="content">
        <div class="head">
          <p class="honorific">${subscriber.displayName} 你好：</p>
        </div>
        <div class="body">
          <div class="summary">
            <p>您的成员申请已提交，请等待审核！</p>
          </div>
        </div>
        <div></div>
      </div>
---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-review-member-submit
spec:
  reasonSelector:
    reasonType: review-member-submit
    language: default
  template:
    title: "您的成员申请已审核完成。"
    rawBody: |
      您的成员申请已审核完成。

      审核描述：${reviewDescription}

    htmlBody: |
      <div class="content">
        <div class="head">
          <p class="honorific">${subscriber.displayName} 你好：</p>
        </div>
        <div class="body">
          <div class="summary">
            <p>您的成员申请已审核完成。</p>
            <p th:if="${reviewDescription != null and reviewDescription != ''}">审核描述：${reviewDescription}</p>
          </div>
        </div>
        <div></div>
      </div>
